config:
  ul-style:
    style: dash
  ul-indent:
    indent: 2
  commands-show-output: false
  no-bare-urls: false
  line-length: false
  no-emphasis-as-header: false
  no-duplicate-header: false
  header-increment: false
  no-blanks-blockquote: false
  no-inline-html: false
  first-line-heading: false
  first-line-h1: false
  code-block-style: false
ignores:
  - '**/node_modules/**'
  - '.github/prompts/*.prompt.md'
  - 'CHANGELOG.md' # generated
  - 'docs/**/*.md'
outputFormatters:
  - - 'markdownlint-cli2-formatter-pretty'
    - appendLink: true
showFound: true
noProgress: false
