name: Node CI

on: [push, pull_request]

jobs:
  test:
    env:
      FORCE_COLOR: '1'
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: '^22.12.0'
          - node-version: '^24.0.0'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: npm test
